
# H2 File 모드
spring.datasource.url=jdbc:h2:file:./data/boxboxdb;DB_CLOSE_DELAY=-1
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA/Hibernate 설정 (유니티에서 보낸 데이터로 테이블 자동 생성)
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

# data.sql 실행

# sql 파일 사용할 때 켜주세요
# spring.sql.init.mode=always 
# spring.jpa.defer-datasource-initialization=true
# spring.sql.init.continue-on-error=false

# mv.db
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=false
spring.sql.init.continue-on-error=true

# OpenWeather
weather.api.base-url=https://api.openweathermap.org
weather.api.key=${OPENWEATHER_API_KEY}
weather.api.units=metric
weather.api.lang=kr

# Default City
weather.default.city-id=SUWON